server:
  port: 9010

spring:
  application:
    name: graph-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: multiservice
    password: 123456
    driver-class-name: org.postgresql.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: '2'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: graph
        hbm2ddl:
          create_namespaces: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    graphiql:
      enabled: true